################################################################
# Global configuration
################################################################

global:
  checkNewVersion: true
  sendAnonymousUsage: true

################################################################
# EntryPoints configuration
################################################################

entryPoints:
  wazuh:
    address: :80

################################################################
# API and dashboard configuration
################################################################

api:
  insecure: true

################################################################
# Docker configuration backend
################################################################

providers:
  swarm:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false